Repository Young-Camper/BE, pull requests merged in 2024-09, with the labels that each got.

#16 feat: 세션 로그인 관련
  build.gradle
  src/main/java/com/youngcamp/server/config/CookieConfig.java
  src/main/java/com/youngcamp/server/config/SecurityConfig.java
  src/main/java/com/youngcamp/server/controller/ExampleController.java
  src/main/java/com/youngcamp/server/controller/SessionController.java
  src/main/java/com/youngcamp/server/service/AdminChecker.java
  src/main/java/com/youngcamp/server/service/SessionService.java
Labels: 💻 찬빈, 🎇 Feat

#15 feat: presignedUrl 발급
  build.gradle
  src/main/java/com/youngcamp/server/controller/PresignedUrlController.java
  src/main/java/com/youngcamp/server/dto/PresignedUrlResponseDTO.java
  src/main/java/com/youngcamp/server/exception/BadRequestException.java
  src/main/java/com/youngcamp/server/exception/GlobalExceptionHandler.java
  src/main/java/com/youngcamp/server/exception/TooManyRequestsException.java
  src/main/java/com/youngcamp/server/service/PresignedUrlService.java
  src/test/java/com/youngcamp/server/service/TestUploadService.java
Labels: 💻 세은, 🎇 Feat

#21 fix: swagger-cors문제 해결
  src/main/java/com/youngcamp/server/ServerApplication.java
Labels: 🔧 Fix, 💻 세은

#18 feat: review CRUD
  build.gradle
  src/main/java/com/youngcamp/server/ServerApplication.java
  src/main/java/com/youngcamp/server/annotation/AdminOnly.java
  src/main/java/com/youngcamp/server/aspect/AdminAspect.java
  src/main/java/com/youngcamp/server/config/AopConfig.java
  src/main/java/com/youngcamp/server/config/ObjectMapperConfig.java
  src/main/java/com/youngcamp/server/config/WebConfig.java
  src/main/java/com/youngcamp/server/controller/PresignedUrlController.java
  src/main/java/com/youngcamp/server/controller/ReviewController.java
  src/main/java/com/youngcamp/server/domain/Review.java
  src/main/java/com/youngcamp/server/dto/PresignedUrlResponseDTO.java
  src/main/java/com/youngcamp/server/dto/ReviewDTO.java
  src/main/java/com/youngcamp/server/exception/GlobalExceptionHandler.java
  src/main/java/com/youngcamp/server/exception/NotFoundException.java
  src/main/java/com/youngcamp/server/helper/ReviewHelper.java
  src/main/java/com/youngcamp/server/repository/ReviewRepository.java
  src/main/java/com/youngcamp/server/security/XSSCharacterEscapes.java
  src/main/java/com/youngcamp/server/service/PresignedUrlService.java
  src/main/java/com/youngcamp/server/service/ReviewService.java
  src/main/java/com/youngcamp/server/utils/SuccessResponse.java
  src/main/java/com/youngcamp/server/validation/ImageUrlPrefix.java
  src/main/java/com/youngcamp/server/validation/ImageUrlPrefixValidator.java
  src/test/java/com/youngcamp/server/ServerApplicationTests.java
Labels: 💻 세은, 🎇 Feat

#17 feat: announcement CRUD
  build.gradle
  src/main/java/com/youngcamp/server/config/SecurityConfig.java
  src/main/java/com/youngcamp/server/controller/AnnouncementController.java
  src/main/java/com/youngcamp/server/domain/Announcement.java
  src/main/java/com/youngcamp/server/dto/AnnouncementRequest.java
  src/main/java/com/youngcamp/server/dto/AnnouncementResponse.java
  src/main/java/com/youngcamp/server/repository/AnnouncementRepository.java
  src/main/java/com/youngcamp/server/service/AnnouncementService.java
  src/test/java/com/youngcamp/server/controller/AnnouncementControllerTest.java
  src/test/java/com/youngcamp/server/repository/AnnouncementRepositoryTest.java
  src/test/java/com/youngcamp/server/service/AnnouncementServiceTest.java
Labels: 💻 주혁, 🎇 Feat

#25 hotfix: 공지사항 목록 및 검색 json변환 에러 해결
  src/main/java/com/youngcamp/server/controller/AnnouncementController.java
  src/main/java/com/youngcamp/server/dto/AnnouncementResponse.java
  src/main/java/com/youngcamp/server/helper/AnnouncementHelper.java
  src/main/java/com/youngcamp/server/service/AnnouncementService.java
  src/test/java/com/youngcamp/server/controller/AnnouncementControllerTest.java
Labels: 🧨 BUG

#34 feat: 공지 읽기 디테일 수정
  src/main/java/com/youngcamp/server/config/SecurityConfig.java
  src/main/java/com/youngcamp/server/dto/AnnouncementDetailProjection.java
  src/main/java/com/youngcamp/server/repository/AnnouncementRepository.java
Labels: 🔧 Fix, 💻 찬빈, 🎇 Feat

#35 Feature/review allow domain
  src/main/java/com/youngcamp/server/validation/ImageUrlPrefixValidator.java
Labels: 🔧 Fix, 💻 찬빈
